language: cpp

matrix:
  include:
  - env:
    - OCPN_TARGET=stretch-armhf
    - OCPN_BRANCH=master
    - DOCKER_IMAGE=raspbian/stretch
    services:
    - docker
    script:
    - travis_wait 40 sleep infinity & bash ./ci/travis-build-raspbian-armhf.sh
  - env:
    - OCPN_TARGET=buster-armhf
    - OCPN_BRANCH=master
    - DOCKER_IMAGE=opencpn/raspbian-buster:plugin_build_tooling
    services:
    - docker
    script:
    - travis_wait 40 sleep infinity & bash ./ci/travis-build-raspbian-armhf.sh
deploy:
  provider: script
  skip_cleanup: true
  script: bash ./ci/cloudsmith-upload.sh
  on:
    tags: false
    all_branches: true
