/***************************************************************************
* Project:  OpenCPN
* Purpose:  Test Plugin Control Dialog
* Author:   Jon Gough
*
* Project:  OpenCPN
*
***************************************************************************
*   Copyright (C) 2013 by David S. Register                               *
*                                                                         *
*   This program is free software; you can redistribute it and/or modify  *
*   it under the terms of the GNU General Public License as published by  *
*   the Free Software Foundation; either version 2 of the License, or     *
*   (at your option) any later version.                                   *
*                                                                         *
*   This program is distributed in the hope that it will be useful,       *
*   but WITHOUT ANY WARRANTY; without even the implied warranty of        *
*   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         *
*   GNU General Public License for more details.                          *
*                                                                         *
*   You should have received a copy of the GNU General Public License     *
*   along with this program; if not, write to the                         *
*   Free Software Foundation, Inc.,                                       *
*   51 Franklin Street, Fifth Floor, Boston, MA 02110-1301,  USA.         *
**************************************************************************/

#ifndef __TPCONTROLDIALOGIMPL_H__
#define __TPCONTROLDIALOGIMPL_H__

/**
 * @file
 * Subclass of tpControlDef, which is generated by wxFormBuilder.
 */

#include "tpControlDialogDef.h"
#include "ODAPI.h"

//    Constants for buttons
    
// forward class definition    
class wxFontDialog;

///////////////////////////////////////////////////////////////////////////////
/// Class tpControlDialogImpl
///////////////////////////////////////////////////////////////////////////////
class tpControlDialogImpl : public tpControlDialogDef 
{
	private:
        double  m_dBoundaryPointRangeRingSteps;
        bool    m_bCreateBoundaryPointHasFocus;
        bool    m_bCreateBoundaryHasFocus;
        wxFontDialog  *m_pfdDialog;
        wxFont  m_DisplayTextFont;
        
	protected:
        // Handlers for ODNewODPointDialogDef events.
        void tpControlOnClickProcessJSON( wxCommandEvent& event );
        void tpControlOKClick( wxCommandEvent& event );
        void tpControlCancelClick( wxCommandEvent& event );
        void OnButtonClickFonts( wxCommandEvent& event );
        void OnButtonClickCreateBoundary( wxCommandEvent& event );
        void OnButtonClickCreateBoundaryPoint( wxCommandEvent& event );
        void OnButtonClickCreateTextPoint( wxCommandEvent& event );
        
	public:
        tpControlDialogImpl( wxWindow *parent );
        void SetDialogSize( void );
        void SetLatLon( double lat, double lon );
        
        bool m_bOK;
        int  m_iSelection;
        
	
};

#endif //__ODNEWODPOINTDIALOGIMPL_H__
